### PR TITLE
Specify only pwd 

### PR DESCRIPTION
**Pull request by Asuforce**
ref: https://github.com/subnixr/minimal/pull/20

I tried `mnml_cwd`, but since I thought pwd was more convenient, I decided pr again.

So please chek this.

### CODE REVIEW

**Comment by subnixr** [comment]
I was busy lately and completely forgot about this PR. I'm sorry.

I understand the use case, but I would integrate the feature in current `mnml_cwd`: display all of the path if `N <= 0`

**Comment by Asuforce** [comment]
Thanks for replying.
Ok, I try to create `mml_cwd` version.

**Comment by Asuforce** [comment]
@subnixr Sorry for late. I fix my pr. Please check again ;)

**Comment by subnixr** [comment]
Thanks!

While the code is good, It's not necessary to add another section in the readme. No worries, I'll fix it

**Pull request merged**
