### PR TITLE
Add Mercurial support to prompt

### LINKED ISSUE #23: Mercurial Support
Is there any support for mercurial or a form to enable it? Thanks

### PR DESCRIPTION
**Pull request by oscarmcm**
Fixes #23

### CODE REVIEW

**Comment by subnixr** [comment]
all good, except for the performance (compared to `mnml_git`):

In a normal directory:

```
$ time ( mnml_git >/dev/null)
( mnml_git > /dev/null; )  0,00s user 0,01s system 98% cpu 0,010 total
$ time ( mnml_hg >/dev/null)
( mnml_hg > /dev/null; )  0,05s user 0,02s system 99% cpu 0,077 total
```

In a git repo:

```
$ time ( mnml_git >/dev/null)
( mnml_git > /dev/null; )  0,00s user 0,01s system 99% cpu 0,015 total
```

In a mercurial repo:

```
$ time ( mnml_hg >/dev/null )
( mnml_hg > /dev/null; )  0,15s user 0,02s system 99% cpu 0,170 total
```

I don't think there is much to do (I guess the problem is with `hg` rather than the widget), but again, I'm not familiar with mercurial.

If there isn't a solution to this problem, I will still merge your PR, but won't include `mnml_hg` by default in the right prompt ([ln 10](https://github.com/subnixr/minimal/pull/24/commits/499dbf9edf0b684e222c19c50831a09bb22ed09d#diff-74898c952e85b00631c5939e4499a472R10))

PS: please also update README.md

**Comment by oscarmcm** [comment]
Hi @subnixr I've updated the docs, disabled the component in the `MNML_RPROMPT` and also improved the branch name speed, the only thing wich is currently unsuported is change the branch color if the branch is dirty.

**Comment by subnixr** [comment]
Sorry for the delay, super busy week.
Good Job with the docs and the performance, but i guess the previous was functionally better. 
Best of both worlds would be awesome!

**Comment by oscarmcm** [comment]
Hi @subnixr update the docs and added the two options for mercurial. 😃

**Comment by subnixr** [comment]
For the moment all good, going to merge!

**Pull request merged**
